Write-Host ""
Write-Host "======================================"
Write-Host " DEPLOYMENT COMPLETE"
Write-Host "======================================"
Write-Host ""
Write-Host "Version:  $env:RELEASE_VERSION"
Write-Host "Release:  C:\Deploy\Releases\$env:RELEASE_VERSION"
Write-Host "Live:     $env:NEW_PORT (old $env:OLD_PORT stopped)"
Write-Host ""
