Write-Host ""
Write-Host "======================================"
Write-Host " DEPLOYMENT COMPLETE"
Write-Host "======================================"
Write-Host ""
Write-Host "Version: $env:VERSION"
Write-Host "Release: C:\Deploy\Releases\$env:VERSION"
Write-Host "Port:    5501"
Write-Host "Caddy:   GREEN"
Write-Host ""
